name: CI
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check for packaging errors
        uses: kirkeaton/action-publint@f9f6fe7af0b7c269bed6a503c31a058b0e2b47f7 # v2.1.6
